/**
 * Theme identity, shared by the no-flash script, the picker and the CSS.
 *
 * Plain module with no directive: the inline script in layout.tsx needs the
 * storage keys at the top of the document, and the client picker needs the
 * list, so neither side can own this.
 *
 * The palettes themselves live in app/themes.css, generated by
 * scripts/themes.mjs. Adding a theme means editing that script, re-running it
 * (which re-checks every contrast pair), and adding a row here.
 */

export const THEME_STORAGE_KEY = "leeeto:theme";
export const MODE_STORAGE_KEY = "leeeto:mode";

export const DEFAULT_THEME = "graphite";

export type ThemeId = "graphite" | "ember" | "cobalt" | "plum" | "moss";
/** "system" follows the OS; the other two override it in both directions. */
export type ModeId = "system" | "light" | "dark";

export const THEMES: {
  id: ThemeId;
  label: string;
  /** Accent in light and dark, for the picker's swatches. */
  light: string;
  dark: string;
}[] = [
  { id: "graphite", label: "Graphite", light: "#0a7350", dark: "#3fc98d" },
  { id: "ember", label: "Ember", light: "#a8400f", dark: "#ff8b52" },
  { id: "cobalt", label: "Cobalt", light: "#1a5cc0", dark: "#6aa5ff" },
  { id: "plum", label: "Plum", light: "#a11d4c", dark: "#ff7ba8" },
  { id: "moss", label: "Moss", light: "#5f6b13", dark: "#bccf4e" },
];

export const MODES: { id: ModeId; label: string }[] = [
  { id: "system", label: "System" },
  { id: "light", label: "Light" },
  { id: "dark", label: "Dark" },
];

/**
 * Runs before first paint, inlined into <head>.
 *
 * Without it the document renders with the default theme for one frame and
 * then snaps to the stored one, which is the flash every theme switcher gets
 * wrong. Written as a string because it has to execute before React exists,
 * and wrapped in try/catch because localStorage throws outright in some
 * privacy modes rather than returning null.
 */
export const themeBootstrapScript = `
(function(){
  try {
    var t = localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)}) || ${JSON.stringify(DEFAULT_THEME)};
    var m = localStorage.getItem(${JSON.stringify(MODE_STORAGE_KEY)}) || "system";
    var el = document.documentElement;
    el.dataset.theme = t;
    if (m === "light" || m === "dark") el.dataset.mode = m;
  } catch (e) {}
})();
`.trim();
